CJAPP/backend/backend/urls.py
from django.conf.urls import  url

from django.urls import  include

from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

from django.urls import path

from djapp import views

from rest_framework.urlpatterns import format_suffix_patterns



from django.contrib.auth import views as auth_views

from django.urls import reverse_lazy, reverse




app_name  ="djapp"

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    
    url(r'^djapp/', include( 'djapp.urls', namespace='djapp')),

   
    
   
    url(r'^djapp/password_reset/$', auth_views.PasswordResetView.as_view(success_url=reverse_lazy('djapp:password_reset_done')), {'template_name': 'djapp/reset_password.html', 'post_reset_redirect': 'djapp:password_reset_done', 'email_template_name': 'djapp/reset_password_email.html'}, name='reset_password'),
    
 
]

if settings.DEBUG:
    urlpatterns+= static(settings.STATIC_URL, document_root= settings.STATIC_ROOT )
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns= format_suffix_patterns(urlpatterns)



CJAPP/backend/djapp/urls.py
from django.urls import include
from django.conf.urls import  url


from .views import HomeView
from .import views

from django.urls import path

from django.urls import reverse_lazy
  
from rest_framework.urlpatterns import format_suffix_patterns

from django.conf import settings
from django.conf.urls.static import static

from django.contrib.auth import views as auth_views




app_name='djapp'

urlpatterns = [
    url(r'^$', views.HomeView, name="homeapp"),

    url(r'^login/$', views.LoginView.as_view(), name='login'),

    url(r'^logout_user/$', views.logout_user, name='logout_user'),
    

    url(r'^posted/(?P<pk>[0-9]+)/$', views.QuestionDetail, name='questiondetail'),

    url(r'^postedtailoring/(?P<pk>[0-9]+)/$', views.QuestionDetail2, name='questiondetail2'),
    
    url(r'^mainpagevisitor/$', views.MainPageDirectVisitors, name='mainpagevisitor'),


  
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.activate_account, name='activate'),

    url(r'^user/$', views.UsersView.as_view(), name= 'user'),

    url(r'^carpentryquestion/$', views.CarpentryCreate.as_view(), name= 'carpentryadded'),

    url(r'^tailoringquestion/$', views.TailoringCreate.as_view(), name= 'tailoringadded'),

    url(r'^posted/(?P<pk>[0-9]+)/addcomment/$', views.addcarpentrycomments, name='addcomment'),

    url(r'^posted/(?P<pk>[0-9]+)/addcommenttailoring/$', views.addtailoringcomments, name='addcomment2'),


   
    url(r'^profile/(?P<pk>\d+)/$', views.view_profile, name='profile'),
    
    url(r'^otherprofile/(?P<pk>\d+)/$', views.view_profile2, name='profile2'),

    url(r'^editprofile/$', views.edit_profile, name='editprofile'),
    
    url(r'^profile/(?P<pk>[0-9]+)/addnotes/$', views.AddNotes, name='AddNotes'),

    url(r'image/(?P<pk>[0-9]+)/$', views.Addimage.as_view(), name='image-add'),

   
    url(r'^(?P<pk>[0-9]+)/delete/$', views.Notesdelete.as_view(), name='notes-delete'),
    
    url(r'^(?P<pk>[0-9]+)/deletecarpentry/$', views.Carpentrydelete.as_view(), name='carpentry-delete'),
    
    url(r'^(?P<pk>[0-9]+)/carpdelete/$', views.carpentrycommentdelete.as_view(), name='carpentrycomments-delete'),

    url(r'^(?P<pk>[0-9]+)/deletetailoring/$', views.Tailoringdelete.as_view(), name='tailoring-delete'),

    url(r'^(?P<pk>[0-9]+)/commentingdeletetailoring/$', views.Tailoringcommentingdelete.as_view(), name='tailoringcomments-delete'),



    url(r'carpentry/(?P<pk>[0-9]+)/$', views.CarpentryUpdate.as_view(), name='carpentry-update'),
    

    url(r'tailoring/(?P<pk>[0-9]+)/$', views.tailoringUpdate.as_view(), name='tailoring-update'),
    
    url(r'^thanks/$', views.thanks, name='thanks'),
    
    
    url (r'^register/$', views.usersignup, name='register'),  

    #change password
    url(r'^change-password/$', views.change_password, name='change_password'),

#change password
    
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name= 'djapp/reset_password.html',email_template_name= 'djapp/reset_password_email.html', success_url=reverse_lazy('djapp:password_reset_done')), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name= 'djapp/reset_password_done.html'), name='password_reset_done'),
    path('password_reset/confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name= 'djapp/reset_password_confirm.html'), name='password_reset_confirm'),
    path('password_reset/complete/', auth_views.PasswordResetCompleteView.as_view(template_name= 'djapp/reset_password_complete.html'), name='password_reset_complete'),
    
   
]


CJAPP/backend/djapp/forms.py
from django.forms import ModelForm

from django.contrib.auth.models import User
from django import forms
from .models import commenting, UserProfile,UserNotes,carpentry,tailoring,tailorcommenting
from django.contrib.auth.forms import UserCreationForm, UserChangeForm


class UserProfileForm( UserCreationForm):
    

    class Meta:
      model  =  UserProfile
      fields = [ 'image','notes']


class ContactForm(forms.Form):

    Your_email = forms.EmailField(required=True)
    
    
    message = forms.CharField(widget=forms.Textarea)

   
class UserForm(UserCreationForm):
    

    class Meta:

      model  = User
      fields = ['username','email','password1','password2']
      email =forms.EmailField(required = True)
    

    def clean_email(self):
        # Get the email
        email = self.cleaned_data.get('email')

        # Check to see if any users already exist with this email as a username.
        try:
            match = User.objects.get(email=email)
        
        except User.MultipleObjectsReturned:
             user = User.objects.filter(email=email).order_by('id')[0]

        except User.DoesNotExist:
            # Unable to find a user, this is fine
            return email

        # A user was found with this as a username, raise an error.
        raise forms.ValidationError('This email address is already in use.')

class CommentForm(forms.ModelForm):
    class Meta:
      model  = commenting
      fields = [  'body']

class tailoringCommentForm(forms.ModelForm):
    class Meta:
     
      model  = tailorcommenting

      fields = [  'body']

class carpentryForm(forms.ModelForm):
    class Meta:
      model  = carpentry
      fields = [  'title','imagedailyupdate','latestcarpentryupdate','linktofurtherreading']


class tailoringForm(forms.ModelForm):
    class Meta:
      model  = tailoring
      fields = [  'title','imagedailyupdate','latesttailoringupdate','linktofurtherreading']

class EditProfileForm(forms.ModelForm):
    
    class Meta:
        model = User
        fields = (
            'email',
            'username'
            

        )

class UserProfileForm(forms.ModelForm):

    class Meta:
        model = UserProfile
        fields = ['image','career_interests']
        

class EditImageForm(forms.ModelForm):
       

    class Meta:
        model = UserProfile
        fields = ['image']
            
class AddNotesForm(forms.ModelForm):
    

    class Meta:
      model  = UserNotes
      fields = [ 'notes']

CJAPP/backend/djapp/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from django.views import generic
# Create your views here.

from django.contrib.contenttypes.models import ContentType
from django.urls import reverse_lazy, reverse
from django.contrib.auth.forms import AuthenticationForm

from .models import carpentry, commenting,UserProfile,UserNotes,tailoring,tailorcommenting
from .forms import UserForm, CommentForm,  EditProfileForm,UserProfileForm, EditImageForm,AddNotesForm,carpentryForm,tailoringForm,tailoringCommentForm,ContactForm
from django.shortcuts import render,redirect,get_object_or_404
from django.views.generic import View
from django.contrib.auth import authenticate,login,logout

from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, DeleteView, \
                                 UpdateView, RedirectView, FormView

from django.db.models import Q
from django.views.generic.edit import FormView

from django.http import HttpResponseRedirect, HttpResponse

from django.contrib.auth.models import User

from django.contrib.auth.decorators import login_required

from django.contrib.auth.mixins import LoginRequiredMixin


from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate

from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.template.loader import render_to_string
from .token_generator import account_activation_token
from django.contrib.auth.models import User
from django.core.mail import EmailMessage

from django.contrib.auth.forms import PasswordChangeForm

from django.contrib.auth import (
    REDIRECT_FIELD_NAME, get_user_model, login as auth_login,
    logout as auth_logout, update_session_auth_hash,
)

from django.core.mail import send_mail, BadHeaderError
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect



class LoginView(FormView):
    template_name = 'djapp/login.html'
    form_class =  AuthenticationForm
    success_url = reverse_lazy('djapp:homeapp')


    def form_valid(self, form):
        login(self.request, form.get_user())
        return HttpResponseRedirect(self.success_url)



@ login_required

def QuestionDetail(request,pk=None):

    carpentrypostsdetail = get_object_or_404(carpentry, pk=pk)
    
   
    users=User.objects.exclude(id= request.user.id)
     
    args={ 'users': users }     
   
    return render(request, 'djapp/carpentryquestionsanddailyfacts.html', {'carpentrypostsdetail':carpentrypostsdetail},args)

@ login_required
def QuestionDetail2(request,pk=None):

    tailoringpostsdetail = get_object_or_404(tailoring, pk=pk)
    
   
    users=User.objects.exclude(id= request.user.id)
     
    args={ 'users': users }     
   
    return render(request, 'djapp/tailoringquestionsanddailyfacts.html', {'tailoringpostsdetail':tailoringpostsdetail},args)
    
    
@ login_required(login_url = '/djapp/mainpagevisitor/')

def HomeView(request):

   
    
    carpentryposts= carpentry.objects.all().order_by('-created')
    
    tailoringposts= tailoring.objects.all().order_by('-created')
    
    
    
    if request.method == 'GET':
        form = ContactForm()
    else:
        form = ContactForm(request.POST)
        if form.is_valid():
            
            Your_email = form.cleaned_data['Your_email']

            message = form.cleaned_data['message']
            to_email=  ('juniorboyboy2@gmail.com')
            try:
                email = EmailMessage(Your_email, message, to=[to_email])
                email.send()
                
            except BadHeaderError:
                return HttpResponse('Invalid header found.')
            return redirect('djapp:thanks')
    
    mydict={'carpentryposts':carpentryposts ,'tailoringposts':tailoringposts,'form': form}

    return render(request, 'djapp/index.html',context=mydict)
 
    
    


@ login_required
def view_profile(request, pk=None):

 

 if pk:
         user = User.objects.get(pk=pk)
         
    
 else:
         
         user = request.user
 args = {'user': user}
 return render(request, 'djapp/user_profile.html', args)




@ login_required
def view_profile2(request, pk=None):

 

 if pk:
         user = User.objects.get(pk=pk)
         
    
 else:
         
         user = request.user
 args = {'user': user}
 return render(request, 'djapp/user_profile2.html', args)


    
class UsersView(LoginRequiredMixin, generic.ListView):

    template_name= 'djapp/users.html'
    context_object_name = 'users'
    def get(self,request):
     
      users=User.objects.exclude(id= request.user.id)
     
      args={ 'users': users }
      return render(request, self.template_name, args)
    



def MainPageDirectVisitors(request):

    carpentryposts= carpentry.objects.all()
    
    tailoringposts= tailoring.objects.all()

    if request.method == 'GET':
        form = ContactForm()
    else:
        form = ContactForm(request.POST)
        if form.is_valid():
            
            Your_email = form.cleaned_data['Your_email']

            message = form.cleaned_data['message']
            to_email=  ('juniorboyboy2@gmail.com')
            try:
                email = EmailMessage(Your_email, message, to=[to_email])
                email.send()
                
            except BadHeaderError:
                return HttpResponse('Invalid header found.')
            return redirect('djapp:thanks')
    
    
    mydict={'carpentryposts':carpentryposts ,'tailoringposts':tailoringposts, 'form': form}

    return render(request, 'djapp/indexvisitor.html',context=mydict)
 
    
    



def usersignup(request):
    if request.method == 'POST':
        form = UserForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.is_active = False
            user.save()

            current_site = get_current_site(request)
            email_subject = 'Activate Your Account'
            message = render_to_string('djapp/activate_account.html', {
                'user': user,
                'domain': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)).decode(),
                'token': account_activation_token.make_token(user),
            })
            to_email = form.cleaned_data.get('email')
            email = EmailMessage(email_subject, message, to=[to_email])
            email.send()

           
           
            user.save()
            
            
            return redirect('djapp:thanksregister')
    else:
        form = UserForm()
    return render(request, 'djapp/signup.html', {'form': form})





@ login_required
def addcarpentrycomments(request, pk=None):
     commentpost = get_object_or_404(carpentry,pk=pk)


     
     if request.method== 'POST':
         form=CommentForm(request.POST)
        
         if form.is_valid():
                commenting = form.save(commit=False)
                commenting.user= request.user
                commenting.posting= commentpost
                
                commenting.save()

                
                return redirect ('djapp:questiondetail', pk=commentpost.pk)
     else:
         form=CommentForm()
        
     return render(request, 'djapp/addcomment.html', {'form':form},)



@ login_required
def addtailoringcomments(request, pk=None):
     commentpost = get_object_or_404(tailoring,pk=pk)


     
     if request.method== 'POST':
         form=tailoringCommentForm(request.POST)
        
         if form.is_valid():
                commenting = form.save(commit=False)
                commenting.user= request.user
                commenting.posting= commentpost
                
                commenting.save()

                
                return redirect ('djapp:questiondetail2', pk=commentpost.pk)
     else:
         form=CommentForm()
        
     return render(request, 'djapp/addtailoringcomment.html', {'form':form},)






class CarpentryCreate(LoginRequiredMixin, CreateView):
    model= carpentry
    fields = [  'title','imagedailyupdate','latestcarpentryupdate','linktofurtherreading']

    def form_valid(self, form):


        form.instance.user = self.request.user
        return super(CarpentryCreate, self).form_valid(form)

class TailoringCreate( LoginRequiredMixin,CreateView):
    model= tailoring
    fields = [  'title','imagedailyupdate','latesttailoringupdate','linktofurtherreading']

    def form_valid(self, form):


        form.instance.user = self.request.user
        return super(TailoringCreate, self).form_valid(form)




class Carpentrydelete(LoginRequiredMixin,DeleteView):
    model= carpentry

    

    success_url= reverse_lazy('djapp:homeapp')


class Tailoringdelete(LoginRequiredMixin,DeleteView):
    model= tailoring
    

    success_url= reverse_lazy('djapp:homeapp')

class carpentrycommentdelete(LoginRequiredMixin,DeleteView):
    model= commenting
    
    

    success_url= reverse_lazy('djapp:homeapp')

class Tailoringcommentingdelete(LoginRequiredMixin,DeleteView):
    model= tailorcommenting
    

    success_url= reverse_lazy('djapp:homeapp')





def logout_user(request):
    logout(request)
    form = UserForm(request.POST or None)
    context = {
        "form": form,
    }
    
    return render(request, 'djapp/logout.html',context)


@ login_required
def edit_profile(request, pk=None):

CJAPP/backend/djapp/templates/djapp/login.html




{% block body%}

{% load static from staticfiles %}

<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">
  
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
 
  {% load staticfiles %}
  
 
  
  <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>

  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

  <!-- Compiled and minified CSS -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
  <title>djangoapp</title>

  
</head>
<style>

  .section{
    padding-top: 4vw;
    padding-bottom: 4vw;
  }
</style>
<body class="grey lighten-3"">

  <!-- NAVBAR -->
  <div class="navbar-fixed">
     <nav class="z-depth-0 yellow lighten-4">
      <div class="nav-wrapper container">
        <a href="{% url 'djapp:mainpagevisitor' %}" class="brand-logo blue-text" style="font-family: cursive;"> <i class="material-icons blue-text">filter_drama</i> Cjapp</a>

            <!-- NAVBAR DROPDOWN -->
        <a href="#" class="sidenav-trigger" data-target="mobile dropdownlinks">
          <i class="material-icons blue-text">menu</i>
        </a>
        
        <a href="{% url 'djapp:register' %}" class="flow-text black-text sidenav-trigger right " style="font-family: cursive;" data-target="modal-signup">Sign up</a>  
        
        <a href="{% url 'djapp:login' %}" class="  flow-text black-text sidenav-trigger right " style="font-family: cursive;" data-target="modal-signup">login</a>  
        
        <ul id="nav-mobile" class="right hide-on-med-and-down">
            
            
            
            <li class="">
              <a href="{% url 'djapp:login' %}" class="grey-text modal-trigger" data-target="modal-login">Login</a>
            </li>
            <li class="">
              <a href="{% url 'djapp:register' %}" class="grey-text modal-trigger" data-target="modal-signup">Sign up</a>
            </li>
          </span>
        </ul>
      </div>
    </nav>
  </div>
  <ul id="mobile dropdownlinks" class="sidenav">
      
      
      <li class="logged-out">
        <a href="{% url 'djapp:login' %}" class="grey-text modal-trigger" data-target="modal-login">Login</a>
      </li>
      <li class="logged-out">
        <a href="{% url 'djapp:register' %}" class="grey-text modal-trigger" data-target="modal-signup">Sign up</a>
      </li>
     
    </span>
  </ul>


  

<!-- Log in form -->



<div class="container" style="margin-top: 40px;">
    

  <div class="row">
      

      <div class="col s12 l10">
        <div class="card">
            <div class="card-image ">
              
              
            </div>
            <div class="card-content">
              <span class="card-title">Login</span>
              
            </div>
            <div class="card-action">
              <form id="login-form"  method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                
                {{form.as_p}}
                
                <button class="btn yellow darken-2 z-depth-0">login to app</button> 

                
              
              </form>
             <br/>
              <a  href='{% url 'djapp:password_reset' %}' class="black-text" >forgot password??</a> 
            </div>
        </div>

        
      </div>

  </div>


</div>
 

  <!-- Compiled and minified JavaScript -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
  
  

  <script>
    $(document).ready(function(){
      $('.sidenav').sidenav();
    });
  </script>

</body>
</html>

{% endblock %}


CJAPP/backend/djapp/templates/djapp/reactapp.html
{% block body %}


      


    

{% load static from staticfiles %}

<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>

  {% load staticfiles %}
  
 
  
  <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>

  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

  <!-- Compiled and minified CSS -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
  <title>djangoapp</title>

  
</head>

<style>
    .row > div{
      padding: 10px;
      background: #ddd;
      border: 1px solid #fff;
      height: 1000px auto;
    }
    .row{
      margin: 40px auto;
    }
</style>

<body class="grey lighten-3"">

  <!-- NAVBAR -->
  <div class="navbar-fixed">
    <nav class="z-depth-0 yellow lighten-4">
      <div class="nav-wrapper container">
        <a href="{% url 'djapp:homeapp' %}" class="brand-logo blue-text" style="font-family: cursive;"> DJapp</a>

            <!-- NAVBAR DROPDOWN -->
        <a href="#" class="sidenav-trigger" data-target="mobile dropdownlinks">
          <i class="material-icons blue-text">menu</i>
        </a>
        
        <a href="{% url 'djapp:AddNotes' pk=user.pk %}" class=" black-text right sidenav-trigger tooltipped" data-tooltip="You"   >
            <i class="material-icons">account_circle</i>
              
        </a>

        <a href="{% url 'djapp:logout_user' %}" class="black-text right sidenav-trigger tooltipped"  data-tooltip="Logout">
        <i class="material-icons">exit_to_app</i>
        </a>
        <ul id="nav-mobile" class="right hide-on-med-and-down">
          <li class="logged-in">
               
            <a  href="{% url 'djapp:AddNotes' pk=user.pk %}" class=" modal-trigger black-text tooltipped" data-target="modal-account" data-tooltip="You">
               
             <i class="material-icons">account_circle</i>
           
           </a>
          
         </li>
          <li class="logged-in">
              <a href="{% url 'djapp:logout_user' %}" class="grey-text" id="logout">Logout</a>
          </li>
            
            
          </span>
        </ul>
      </div>
    </nav>
  </div>
  <ul id="mobile dropdownlinks" class="sidenav">
    <li class="logged-in">
      <a href="{% url 'djapp:AddNotes' pk=user.pk %}" class="blue-text modal-trigger" style="font-family: cursive;" data-target="modal-account"> {{user.username}} <i class="material-icons">person</i></a>
    </li>
      <li class="logged-in">
        <a href="{% url 'djapp:logout_user' %}" class="grey-text" id="logout">Logout</a>
      </li>
      
      
    </span>
  </ul>






  <div class="container">
    <h1  class="flow-text" >CARPENTRY BUSINESS APP ON {{ carpentrypostsdetail.created|date:"F,d,Y"}} </h1>
    {% if user.is_superuser %}
    

    

    
        
          <form  action="{% url 'djapp:carpentry-delete' carpentrypostsdetail.id %}" method="post" >


              {% csrf_token %}
              
                <button  type="submit" <i class="material-icons">delete_forever</i></button>
                    
                
             
          </form>
        

        
          <form  action="{% url 'djapp:carpentry-update' carpentrypostsdetail.id %}" method="post" >


              {% csrf_token %}
              
                <button  type="submit" <i class="material-icons">edit</i></button>
                    
                
              
          </form>
       
         
    {%endif%}
    <div class="row">

    

    
      <div class="col s12 m6 l6">
          <p class="red-text"> DAILY QUESTION</p>
        <hr>
          <p class=" flow-text black-text">{{ carpentrypostsdetail.title }} on {{ carpentrypostsdetail.created }} by {{ carpentrypostsdetail.user }} </p>
          <hr>

          <p class="red-text">ANSWERS:</p>

        {%for comment in carpentrypostsdetail.commention.all %}
          
          <p class="red-text"> Answer:</p> {{comment.body}}
          
          
          <p class="blue-text">{{comment.created}} by  {{comment.user}}<i class="material-icons">person_pin</i></p>
         

          
          
        {%endfor%}
        
       

         
       <br>
        
        <a href="{% url 'djapp:addcomment'  pk=carpentrypostsdetail.pk %}" class="white-text  btn" >ANSWER THE QUESTION</a>
       
        <hr>
       
        <p><a href="{% url 'djapp:user'  %}" class="white-text  btn" >SEE OTHER USERS AND THEIR PROFILE</a></p>
                 
       

      </div>
    
      <div class="col s12 m6 l6">

         
           
        <p  class="red-text">Daily facts about Carpentry in Nigeria on {{ carpentrypostsdetail.created|date:"F,d,Y"}}  </p>
        <hr>
        </br>
        <div class="card">
            <div class="card-image" >
              <img src="{{ carpentrypostsdetail.imagedailyupdate.url }}" alt="">
              
            </div>

            {%for comment in carpentry.commention.all %}
             <p>{{comment.body}}</p> 
             <p> by {{comment.user}}</p>
            {%endfor%}
            

            <div class="card-content">
              <span class="card-title">posted by {{carpentrypostsdetail.user}} </span>
               
            </div>
            <div class="card-action">
                <p><a href="#" class="grey-text modal-trigger" data-target="business">{{ carpentrypostsdetail.latestcarpentryupdate }}</a></p>
                
               
                
            </div>
        </div>
        
      </div>

      
    
    </div>
    
  </div>
 

  

  <!-- Compiled and minified JavaScript -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
  
  

  <script>
    $(document).ready(function(){
      $('.sidenav').sidenav();
    });
  </script>

 



</body>
</html>

{%endblock%}






  

CJAPP/backend/djapp/templates/djapp/reset_password_email.html
{% load i18n %}{% autoescape off %}
{% blocktrans %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktrans %}

{% trans "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'djapp:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% trans "Your username, in case you've forgotten:" %} {{ user.get_username }}

{% trans "Thanks for using our site!" %}

{% blocktrans %}The {{ site_name }} team{% endblocktrans %}

{% endautoescape %}